export const ADD_CART_POSITION = 'ADD_CART_POSITION';
export const DELETE_CART_POSITION = 'DELETE_CART_POSITION';
export const EMPTY_CART = 'EMPTY_CART';
export const DECREMENT_CART_POSITION = 'DECREMENT_CART_POSITION';
export const INCREMENT_CART_POSITION = 'INCREMENT_CART_POSITION';
